[package]
name = "net_pong"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.18.0"
relay = { path = "../relay" }
serde = { version = "1", features = ["derive"] }
postcard = { version = "1", features = ["alloc"] }
